(()=>{
const V={catalog:[],external:[],current:null,feedLikes:new Set()};
const q=id=>document.getElementById(id);
const e=v=>typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,'');
const logged=()=>typeof user!=='undefined'&&!!user;

function installCss(){if(document.querySelector('link[href="/community-v6.css"]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='/community-v6.css';document.head.appendChild(l)}
function setVersion(){const x=document.querySelector('.version-pill');if(x)x.textContent='v6 Community'}

function installFeed(){const home=q('home');if(!home||q('communityFeed'))return;const box=document.createElement('div');box.className='community-block';box.innerHTML=`<div class="community-head"><div><div class="eyebrow">COMMUNITY</div><h2>Aktuelle Fänge</h2></div><span class="community-badge">● LIVE</span></div><div id="communityFeed" class="feed-grid"><div class="community-empty">Community wird geladen …</div></div>`;home.appendChild(box);loadFeed()}

async function loadFeed(){const el=q('communityFeed');if(!el)return;try{const {data,error}=await sb.from('catches').select('id,user_id,species,caught_on,caught_at,length_cm,weight_kg,bait,method,water_id,water_name,notes,created_at,released_location,latitude,longitude').eq('visibility','public').order('created_at',{ascending:false}).limit(16);if(error)throw error;const rows=data||[];if(!rows.length){el.innerHTML='<div class="community-empty">Noch keine öffentlichen Fänge. Der erste geteilte Fang erscheint hier.</div>';return}const uids=[...new Set(rows.map(x=>x.user_id))],ids=rows.map(x=>x.id);let profiles=[],likes=[],comments=[];if(uids.length){const r=await sb.from('profiles').select('id,username,display_name').in('id',uids);profiles=r.data||[]}if(ids.length){const [lr,cr]=await Promise.all([sb.from('catch_likes').select('catch_id,user_id').in('catch_id',ids),sb.from('catch_comments').select('id,catch_id,user_id,body,created_at').in('catch_id',ids)]);likes=lr.data||[];comments=cr.data||[]}const pm=Object.fromEntries(profiles.map(p=>[p.id,p]));V.feedLikes=new Set(likes.filter(x=>logged()&&x.user_id===user.id).map(x=>x.catch_id));el.innerHTML=rows.map(c=>{const p=pm[c.user_id]||{},lc=likes.filter(x=>x.catch_id===c.id).length,cc=comments.filter(x=>x.catch_id===c.id).length;return `<article class="feed-card"><div class="feed-top"><div style="display:flex;gap:9px;align-items:center"><span class="avatar-dot">${e((p.display_name||p.username||'A').slice(0,1).toUpperCase())}</span><div><div class="feed-name">${e(p.display_name||p.username||'Angler')}</div><div class="feed-meta">${e(c.caught_on||'')}</div></div></div><span class="community-badge">öffentlich</span></div><div class="fish-title">🐟 ${e(c.species)}</div><div class="catch-metrics">${c.length_cm?`<span class="mini-pill">${e(c.length_cm)} cm</span>`:''}${c.weight_kg?`<span class="mini-pill">${e(c.weight_kg)} kg</span>`:''}${c.method?`<span class="mini-pill">${e(c.method)}</span>`:''}${c.bait?`<span class="mini-pill">Köder: ${e(c.bait)}</span>`:''}</div>${c.water_name?`<div class="water-meta">📍 ${e(c.water_name)}${c.released_location?' · Fangort freigegeben':''}</div>`:''}${c.notes?`<p class="muted">${e(c.notes)}</p>`:''}<div class="social-row"><button class="social-btn ${V.feedLikes.has(c.id)?'active':''}" onclick="v6ToggleLike('${c.id}')">♥ ${lc}</button><button class="social-btn" onclick="v6Comment('${c.id}')">💬 ${cc}</button>${c.water_id?`<button class="social-btn" onclick="v6OpenWaterId('${c.water_id}')">Gewässer</button>`:''}</div></article>`}).join('')}catch(err){console.error(err);el.innerHTML='<div class="community-empty">Feed konnte nicht geladen werden.</div>'}}

async function toggleLike(id){if(!logged())return typeof msg==='function'&&msg('Bitte zuerst anmelden.',true);if(V.feedLikes.has(id))await sb.from('catch_likes').delete().eq('catch_id',id).eq('user_id',user.id);else await sb.from('catch_likes').insert({catch_id:id,user_id:user.id});loadFeed()}
async function comment(id){if(!logged())return typeof msg==='function'&&msg('Bitte zuerst anmelden.',true);const body=prompt('Kommentar schreiben:');if(!body?.trim())return;await sb.from('catch_comments').insert({catch_id:id,user_id:user.id,body:body.trim()});loadFeed()}
window.v6ToggleLike=toggleLike;window.v6Comment=comment;

function installWaterPanel(){const sec=q('search');if(!sec||q('communityWaterPanel'))return;const p=document.createElement('div');p.id='communityWaterPanel';p.className='water-profile hidden';sec.appendChild(p)}

async function v6SearchWater(){const input=q('waterSearch'),out=q('results'),term=input?.value.trim();if(!term||!out)return;out.innerHTML='<div class="community-empty">Gewässer werden gesucht …</div>';try{const [db,ph]=await Promise.all([sb.from('waters').select('*').ilike('name',`%${term}%`).limit(12),fetch('https://photon.komoot.io/api/?limit=10&lang=de&q='+encodeURIComponent(term)).then(r=>r.json()).catch(()=>({features:[]}))]);V.catalog=db.data||[];V.external=(ph.features||[]).filter(f=>{const p=f.properties||{},t=String(p.osm_value||p.type||'').toLowerCase();return !t||['water','lake','river','reservoir','canal','pond','stream'].some(x=>t.includes(x))}).map((f,i)=>{const p=f.properties||{},c=f.geometry.coordinates;return{_external:true,_idx:i,source_key:p.osm_id?`osm:${p.osm_type||''}:${p.osm_id}`:null,name:p.name||term,water_type:p.osm_value||p.type||'Gewässer',locality:p.city||p.district||p.county||'',state:p.state||'',country:p.country||'DE',latitude:c[1],longitude:c[0],source_name:'OpenStreetMap / Photon',source_license:'ODbL'}});const cards=[...V.catalog.map((w,i)=>waterCard(w,'catalog',i)),...V.external.slice(0,8).map((w,i)=>waterCard(w,'external',i))];out.className='water-results-v6';out.innerHTML=cards.join('')||'<div class="community-empty">Kein Gewässer gefunden.</div>'}catch(err){console.error(err);out.innerHTML='<div class="community-empty">Suche fehlgeschlagen.</div>'}}
function waterCard(w,src,i){return `<div class="water-card" onclick="v6OpenWaterByIndex('${src}',${i})"><div class="water-card-top"><div><b>${e(w.name)}</b><div class="water-meta">${e([w.water_type,w.locality,w.state].filter(Boolean).join(' · '))}</div></div><span class="community-badge">${src==='catalog'?'AngelLog':'Karte'}</span></div><div class="water-tags"><span class="water-tag">📍 ${Number(w.latitude||0).toFixed(3)}, ${Number(w.longitude||0).toFixed(3)}</span>${w.guest_card_url?'<span class="water-tag">🎫 Gastkarte</span>':''}</div></div>`}
window.v6OpenWaterByIndex=(src,i)=>openWater(src==='catalog'?V.catalog[i]:V.external[i]);
try{searchWater=v6SearchWater}catch{window.searchWater=v6SearchWater}

async function ensureWater(w){if(w.id)return w;if(!logged())return w;const row={source_key:w.source_key||`point:${w.name}:${Number(w.latitude).toFixed(5)}:${Number(w.longitude).toFixed(5)}`,name:w.name,water_type:w.water_type||null,locality:w.locality||null,state:w.state||null,country:w.country||'DE',latitude:w.latitude,longitude:w.longitude,source_name:w.source_name||'Karten-Suche',source_license:w.source_license||null,created_by:user.id};const {data,error}=await sb.from('waters').upsert(row,{onConflict:'source_key'}).select().single();return error?w:data}
async function openWater(w){if(!w)return;w=await ensureWater(w);V.current=w;if(typeof selected!=='undefined')selected={name:w.name,lat:+w.latitude,lng:+w.longitude,waterId:w.id||null};const info=q('selectedInfo');if(info)info.innerHTML=`<b>${e(w.name)}</b><br><span class="small">${e([w.water_type,w.locality,w.state].filter(Boolean).join(' · '))}</span>`;const p=q('communityWaterPanel');if(!p)return;p.classList.remove('hidden');p.innerHTML=`<div class="water-profile-grid"><div><div class="eyebrow">GEWÄSSERPROFIL</div><h2 style="margin:5px 0">${e(w.name)}</h2><div class="water-meta">${e([w.water_type,w.locality,w.state].filter(Boolean).join(' · '))}</div><div id="v6WaterRating" class="rating" style="margin-top:7px">Bewertungen werden geladen …</div><div class="profile-actions"><button class="primary" onclick="v6FollowWater()">☆ Folgen</button><button class="secondary" onclick="v6Checkin()">📍 Einchecken</button><button class="secondary" onclick="v6ShowWaterMap()">🗺 Karte</button></div><div class="profile-section"><h3>Fischarten</h3><div id="v6Fish">Lädt …</div>${logged()?'<button class="social-btn" style="margin-top:8px" onclick="v6AddFish()">+ Fischart ergänzen</button>':''}</div><div class="profile-section"><h3>Gastkarte & Bestimmungen</h3><div class="muted">${w.guest_card_info?e(w.guest_card_info):'Noch keine Gastkarten-Angabe.'}</div><div class="muted" style="margin-top:6px">${w.regulations?e(w.regulations):'Noch keine Angelbestimmungen hinterlegt.'}</div>${w.guest_card_url?`<a class="secondary-link" target="_blank" rel="noopener" href="${e(w.guest_card_url)}">Gastkarte öffnen</a>`:''}</div><div class="profile-section"><h3>Bewerten</h3><div class="buttons"><select id="v6Rating" style="max-width:150px"><option value="5">5 Sterne</option><option value="4">4 Sterne</option><option value="3">3 Sterne</option><option value="2">2 Sterne</option><option value="1">1 Stern</option></select><button class="secondary" onclick="v6RateWater()">Speichern</button></div></div></div><div><div class="profile-section" style="margin-top:0;padding-top:0;border-top:0"><h3>Aktuelle Bedingungen</h3><div id="v6Conditions" class="conditions-grid"><div class="community-empty">Lädt …</div></div></div><div class="profile-section"><h3>Fangstatistik</h3><div id="v6Stats">Lädt …</div></div><div class="source-note">Datenquellen werden je Feld ausgewiesen. Community-Statistiken beruhen ausschließlich auf freigegebenen AngelLog-Fängen.</div></div></div>`;await Promise.all([loadWaterMeta(w),loadConditions(w),loadWaterStats(w)])}

async function openWaterId(id){const {data}=await sb.from('waters').select('*').eq('id',id).single();if(data){if(typeof show==='function')show('search');openWater(data)}}window.v6OpenWaterId=openWaterId;
async function loadWaterMeta(w){if(!w.id){q('v6Fish').innerHTML='<span class="muted">Anmelden, um dieses Gewässer als Community-Profil anzulegen.</span>';q('v6WaterRating').textContent='Noch kein AngelLog-Profil';return}const [fr,rr]=await Promise.all([sb.from('water_fish_species').select('species').eq('water_id',w.id),sb.from('water_reviews').select('rating').eq('water_id',w.id)]);const fish=fr.data||[],ratings=rr.data||[],avg=ratings.length?(ratings.reduce((a,b)=>a+b.rating,0)/ratings.length).toFixed(1):null;q('v6Fish').innerHTML=fish.length?fish.map(x=>`<span class="water-tag">🐟 ${e(x.species)}</span>`).join(' '):'<span class="muted">Noch keine Fischarten eingetragen.</span>';q('v6WaterRating').textContent=avg?`★ ${avg} · ${ratings.length} Bewertungen`:'Noch keine Bewertungen'}

function moon(){const days=(Date.now()-Date.UTC(2000,0,6,18,14))/86400000,age=((days%29.53058867)+29.53058867)%29.53058867;const names=['Neumond','zunehmende Sichel','erstes Viertel','zunehmender Mond','Vollmond','abnehmender Mond','letztes Viertel','abnehmende Sichel'];return names[Math.round(age/29.53058867*8)%8]}
async function loadConditions(w){const el=q('v6Conditions');if(!el||!Number.isFinite(+w.latitude)||!Number.isFinite(+w.longitude))return;try{const [weather,pegel]=await Promise.all([fetch(`https://api.open-meteo.com/v1/forecast?latitude=${w.latitude}&longitude=${w.longitude}&current=temperature_2m,cloud_cover,pressure_msl,wind_speed_10m,precipitation&daily=sunrise,sunset&timezone=auto&forecast_days=1`).then(r=>r.json()),fetch(`/api/pegel-nearby?lat=${w.latitude}&lng=${w.longitude}`).then(r=>r.json()).catch(()=>({stations:[]}))]);const c=weather.current||{},st=pegel.stations?.[0],m=st?.measurement;el.innerHTML=`<div class="condition-card"><span>Temperatur</span><b>${c.temperature_2m==null?'–':Math.round(c.temperature_2m)+' °C'}</b></div><div class="condition-card"><span>Wind</span><b>${c.wind_speed_10m==null?'–':Math.round(c.wind_speed_10m)+' km/h'}</b></div><div class="condition-card"><span>Luftdruck</span><b>${c.pressure_msl==null?'–':Math.round(c.pressure_msl)+' hPa'}</b></div><div class="condition-card"><span>Mond</span><b>${moon()}</b></div><div class="condition-card"><span>Sonnenaufgang</span><b>${weather.daily?.sunrise?.[0]?.slice(-5)||'–'}</b></div><div class="condition-card"><span>Sonnenuntergang</span><b>${weather.daily?.sunset?.[0]?.slice(-5)||'–'}</b></div><div class="condition-card"><span>Nächster Pegel</span><b>${m?.value!=null?`${m.value} ${m.unit||'cm'}`:'–'}</b><span>${e(st?`${st.water||''} · ${st.name} · ${st.distanceKm.toFixed(1)} km`:'kein PEGELONLINE-Pegel')}</span></div><div class="condition-card"><span>Bewölkung</span><b>${c.cloud_cover==null?'–':Math.round(c.cloud_cover)+' %'}</b></div>`}catch(err){console.error(err);el.innerHTML='<div class="community-empty">Bedingungen konnten nicht geladen werden.</div>'}}

function counts(rows,key){const m={};for(const r of rows){const v=r[key];if(v)m[v]=(m[v]||0)+1}return Object.entries(m).sort((a,b)=>b[1]-a[1])}
function ranking(title,a){if(!a.length)return `<div class="muted">Noch zu wenig Daten für ${title}.</div>`;const max=a[0][1];return `<div class="ranking">${a.slice(0,5).map(([k,n])=>`<div class="ranking-row"><span>${e(k)}</span><span class="rank-bar"><i style="width:${Math.round(n/max*100)}%"></i></span><b>${n}</b></div>`).join('')}</div>`}
async function loadWaterStats(w){const el=q('v6Stats');if(!el)return;let query=sb.from('catches').select('species,method,bait,caught_on,caught_at,length_cm,weight_kg').eq('visibility','public');query=w.id?query.eq('water_id',w.id):query.ilike('water_name',w.name);const {data,error}=await query.limit(2000);if(error){el.innerHTML='<div class="community-empty">Statistik konnte nicht geladen werden.</div>';return}const rows=data||[];const species=counts(rows,'species'),methods=counts(rows,'method'),baits=counts(rows,'bait');el.innerHTML=`<div class="stats-grid"><div class="stat-box"><b>${rows.length}</b><small>öffentliche Fänge</small></div><div class="stat-box"><b>${species.length}</b><small>Fischarten</small></div><div class="stat-box"><b>${rows.filter(x=>x.length_cm).length}</b><small>Fänge mit Länge</small></div></div><div class="profile-section"><h3>Top Fischarten</h3>${ranking('Fischarten',species)}</div><div class="profile-section"><h3>Erfolgreiche Methoden</h3>${ranking('Methoden',methods)}</div><div class="profile-section"><h3>Top Köder</h3>${ranking('Köder',baits)}</div>`}

async function followWater(){const w=V.current;if(!w?.id||!logged())return typeof msg==='function'&&msg('Bitte anmelden und ein AngelLog-Gewässerprofil öffnen.',true);const {data}=await sb.from('water_follows').select('water_id').eq('water_id',w.id).eq('user_id',user.id).maybeSingle();if(data)await sb.from('water_follows').delete().eq('water_id',w.id).eq('user_id',user.id);else await sb.from('water_follows').insert({water_id:w.id,user_id:user.id});typeof msg==='function'&&msg(data?'Gewässer nicht mehr gefolgt.':'Gewässer wird jetzt gefolgt.')}
async function checkin(){const w=V.current;if(!w?.id||!logged())return typeof msg==='function'&&msg('Bitte anmelden.',true);await sb.from('water_checkins').insert({water_id:w.id,user_id:user.id,visibility:'public'});typeof msg==='function'&&msg('Check-in gespeichert.')}
async function rateWater(){const w=V.current;if(!w?.id||!logged())return typeof msg==='function'&&msg('Bitte anmelden.',true);const rating=+q('v6Rating').value;await sb.from('water_reviews').upsert({water_id:w.id,user_id:user.id,rating},{onConflict:'water_id,user_id'});loadWaterMeta(w)}
async function addFish(){const w=V.current;if(!w?.id||!logged())return;const species=prompt('Welche Fischart kommt hier vor?');if(!species?.trim())return;await sb.from('water_fish_species').upsert({water_id:w.id,species:species.trim(),created_by:user.id},{onConflict:'water_id,species'});loadWaterMeta(w)}
function showWaterMap(){const w=V.current;if(!w)return;if(typeof show==='function')show('mapsec');setTimeout(()=>{if(typeof initMap==='function')initMap();if(typeof map!=='undefined'&&map)map.setView([w.latitude,w.longitude],14)},100)}
Object.assign(window,{v6FollowWater:followWater,v6Checkin:checkin,v6RateWater:rateWater,v6AddFish:addFish,v6ShowWaterMap:showWaterMap});

function installSharing(){const form=q('catchForm');if(!form||q('catchVisibility'))return;const anchor=q('catchPhoto')?.previousElementSibling||form.querySelector('button.primary');const wrap=document.createElement('div');wrap.className='share-options';wrap.innerHTML=`<div><label>Fang teilen</label><select id="catchVisibility"><option value="private">Privat</option><option value="public">Öffentlich in Community</option></select></div><label class="check-line"><input id="releaseLocation" type="checkbox"> genauen Fangort bei öffentlichen Fängen freigeben</label>`;anchor?.insertAdjacentElement('beforebegin',wrap);form.addEventListener('submit',communityCatchSubmit,true)}
async function weatherSnapshot(lat,lng){if(!Number.isFinite(lat)||!Number.isFinite(lng))return null;try{const d=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lng}&current=temperature_2m,cloud_cover,pressure_msl,wind_speed_10m,precipitation&timezone=auto`).then(r=>r.json());return d.current||null}catch{return null}}
async function communityCatchSubmit(ev){ev.preventDefault();ev.stopImmediatePropagation();if(!logged())return typeof msg==='function'&&msg('Bitte zuerst anmelden.',true);const visibility=q('catchVisibility')?.value||'private',release=!!q('releaseLocation')?.checked;let photo=null;const file=q('catchPhoto')?.files?.[0];if(file){const ext=(file.name.split('.').pop()||'jpg').toLowerCase(),path=`${user.id}/${crypto.randomUUID()}.${ext}`,up=await sb.storage.from('catch-photos').upload(path,file,{contentType:file.type||'image/jpeg'});if(up.error)return msg('Foto-Upload fehlgeschlagen: '+up.error.message,true);photo=path}let waterId=null,lat=null,lng=null;if(V.current&&q('catchWater')?.value.trim().toLowerCase()===String(V.current.name).toLowerCase()){waterId=V.current.id||null;if(release){lat=+V.current.latitude;lng=+V.current.longitude}}else if(typeof selected!=='undefined'&&selected&&q('catchWater')?.value.trim().toLowerCase()===String(selected.name||'').toLowerCase()){waterId=selected.waterId||null;if(release){lat=+selected.lat;lng=+selected.lng}}const snap=await weatherSnapshot(lat,lng);const row={user_id:user.id,species:q('species').value,caught_on:q('catchDate').value,length_cm:q('length').value||null,weight_kg:q('weight').value||null,bait:q('bait').value||null,method:q('method').value||null,water_name:q('catchWater').value||null,notes:q('catchNotes').value||null,photo_url:photo,water_id:waterId,visibility,released_location:release,latitude:release?lat:null,longitude:release?lng:null,weather_snapshot:snap};const {error}=await sb.from('catches').insert(row);if(error){if(photo)await sb.storage.from('catch-photos').remove([photo]);return msg(error.message,true)}formReset();await syncAll();msg(visibility==='public'?'Fang gespeichert und in der Community geteilt.':'Fang privat gespeichert.');loadFeed();if(V.current)loadWaterStats(V.current)}
function formReset(){const f=q('catchForm');f.reset();q('catchDate').value=new Date().toISOString().slice(0,10);if(q('catchVisibility'))q('catchVisibility').value='private'}

function init(){installCss();setVersion();installFeed();installWaterPanel();installSharing();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
