(()=>{
  const q=s=>document.querySelector(s), safe=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  let intelToken=0;
  function inject(){
    const water=q('#aaWaterScreen');if(!water||q('#intelForecast'))return;
    const factor=water.querySelector('.aa-factor');
    const forecast=document.createElement('section');forecast.id='intelForecast';forecast.className='intel-wrap';forecast.innerHTML=`<h3 class="intel-title">Angelbedingungen</h3><div id="intelForecastBody" class="intel-empty">Fangprognose wird geladen …</div><div class="intel-source">Wetterdaten: Open-Meteo · Fangfaktor: AngelLog-Heuristik</div>`;
    factor?.insertAdjacentElement('afterend',forecast);
    const stats=document.createElement('section');stats.id='intelStats';stats.className='intel-wrap';stats.innerHTML=`<h3 class="intel-title">Köder & Methoden</h3><div id="intelStatsBody" class="intel-empty">Communitystatistik wird geladen …</div><div class="intel-note">Die Statistik verwendet ausschließlich öffentliche AngelLog-Fänge, die diesem Gewässer zugeordnet sind.</div>`;
    forecast.insertAdjacentElement('afterend',stats);
    const community=document.createElement('section');community.id='intelCommunity';community.className='intel-community';community.innerHTML=`<h3 class="intel-title">Community-Fänge an diesem Gewässer</h3><div id="intelCommunityBody" class="intel-empty" style="padding:0 20px 20px">Fänge werden geladen …</div>`;
    stats.insertAdjacentElement('afterend',community);
    const sheet=q('#aaSheet');if(sheet&&!q('#aaBait')){
      const btn=q('#aaSaveCatch');const wrap=document.createElement('div');const pref=window.getAngelLogPreferences?.()||{};wrap.innerHTML=`<input id="aaWeight" type="number" step="0.01" placeholder="Gewicht in kg (optional)"><input id="aaBait" placeholder="Köder, z. B. Gummifisch"><select id="aaMethod"><option value="">Methode auswählen</option><option>Spinning</option><option>Grund</option><option>Pose</option><option>Vertikal</option><option>Fliege</option><option>Sonstiges</option></select><small id="aaCatchPrivacyHint" style="display:block;color:#aaa;margin:6px 0">Sichtbarkeit für diesen Fang</small><select id="aaCatchVisibility"><option value="public">Öffentlich · im Community-Feed sichtbar</option><option value="private">Privat · nur für dich</option></select>`;while(wrap.firstChild)btn.parentNode.insertBefore(wrap.firstChild,btn);q('#aaCatchVisibility').value=pref.default_catch_visibility||'public'
    }
  }
  async function isPro(){
    try{if(!aaUser)return false;const {data}=await sb.from('subscription_entitlements').select('tier,status').eq('user_id',aaUser.id).maybeSingle();return data?.tier==='pro'&&['active','trialing','grace_period'].includes(data?.status)}catch{return false}
  }
  function fmtWindow(w){return w?`${safe(w.from)}–${safe(w.to)}`:'–'}
  function scoreLabel(v){if(v>=8)return'Sehr gut';if(v>=6.5)return'Gut';if(v>=5)return'Mittel';return'Schwierig'}
  async function loadForecast(w,token){
    const body=q('#intelForecastBody');if(!body)return;
    try{
      const r=await fetch(`/api/fishing-forecast?lat=${encodeURIComponent(w.latitude)}&lon=${encodeURIComponent(w.longitude)}`,{cache:'no-store'}),d=await r.json();if(token!==intelToken)return;if(!r.ok)throw new Error(d.error||'Fehler');
      const pro=await isPro(),cur=d.current||{},today=d.days?.[0],tomorrow=d.days?.[1],hours=(d.hours||[]).filter(x=>new Date(x.time).getTime()>=Date.now()).slice(0,15);
      if(q('#aaFactorScore'))q('#aaFactorScore').textContent=(cur.score??today?.average??'–');
      const bars=q('#aaBars');if(bars){bars.innerHTML=hours.map(x=>`<i title="${safe(String(x.time).slice(11,16))}: ${safe(x.score)}" style="height:${Math.max(12,(x.score||1)*10)}%"></i>`).join('')}
      body.className='';body.innerHTML=`<div class="intel-current"><div class="intel-score" style="--score:${Number(cur.score||0)}"><strong>${safe(cur.score??'–')}</strong><small>/ 10</small></div><div><b style="font-size:20px">${scoreLabel(Number(cur.score||0))}e Bedingungen</b><div class="intel-kpis"><div class="intel-kpi"><b>${safe(cur.temperature??'–')} °C</b><span>Temperatur</span></div><div class="intel-kpi"><b>${safe(cur.pressure??'–')} hPa</b><span>Luftdruck</span></div><div class="intel-kpi"><b>${safe(cur.wind??'–')} km/h</b><span>Wind</span></div><div class="intel-kpi"><b>${safe(cur.precipitation_probability??'–')} %</b><span>Regenrisiko</span></div></div></div></div><div class="intel-weather-bars">${hours.map(x=>`<i style="height:${Math.max(8,(x.score||1)*10)}%" title="${safe(String(x.time).slice(11,16))} · ${safe(x.score)}"></i>`).join('')}</div><div class="intel-days"><div class="intel-day"><h4>Heute</h4><div class="intel-day-score">${safe(today?.best??'–')}</div><div class="intel-window">Bestes Fenster: ${fmtWindow(today?.windows?.[0])}</div></div><div class="intel-day"><h4>Morgen</h4><div class="intel-day-score">${safe(tomorrow?.best??'–')}</div><div class="intel-window">Bestes Fenster: ${fmtWindow(tomorrow?.windows?.[0])}</div>${pro?'':`<div class="intel-lock"><b>PRO · MORGEN & 48H</b><button onclick="window.openPro&&openPro()">Freischalten</button></div>`}</div></div><div class="intel-note">${safe(d.disclaimer||'Heuristische Prognose; keine Fanggarantie.')}</div>`;
    }catch(e){if(token===intelToken){body.className='intel-empty';body.textContent='Fangprognose konnte gerade nicht geladen werden.'}}
  }
  function methodName(v){const s=String(v||'').trim().toLowerCase();if(!s)return null;if(/spinn/.test(s))return'Spinning';if(/grund/.test(s))return'Grund';if(/pose|posen/.test(s))return'Pose';if(/vertikal/.test(s))return'Vertikal';if(/flieg|fly/.test(s))return'Fliege';return String(v).trim()}
  function topCounts(rows,getter,limit=5){const m=new Map();for(const r of rows){const raw=getter(r);if(!raw)continue;const key=String(raw).trim();if(!key)continue;const match=[...m.keys()].find(k=>k.toLowerCase()===key.toLowerCase())||key;m.set(match,(m.get(match)||0)+1)}const total=[...m.values()].reduce((a,b)=>a+b,0);return [...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,limit).map(([name,count])=>({name,count,pct:total?Math.round(count/total*100):0}))}
  function barRows(items){return items.map(x=>`<div class="intel-row"><div class="intel-row-head"><span>${safe(x.name)}</span><b>${x.pct}%</b></div><div class="intel-track"><div class="intel-fill" style="width:${x.pct}%"></div></div></div>`).join('')}
  async function loadCommunity(id,token){
    const stats=q('#intelStatsBody'),feed=q('#intelCommunityBody');
    const {data,error}=await sb.from('catches').select('id,user_id,species,caught_on,caught_at,length_cm,weight_kg,bait,method,notes,photo_url,created_at').eq('water_id',id).eq('visibility','public').order('created_at',{ascending:false}).limit(250);if(token!==intelToken)return;
    if(error){if(stats)stats.textContent='Statistik konnte nicht geladen werden.';if(feed)feed.textContent='Community-Fänge konnten nicht geladen werden.';return}
    const rows=data||[],methods=topCounts(rows,r=>methodName(r.method)),baits=topCounts(rows,r=>r.bait),pro=await isPro();
    if(stats){stats.className='';const noData=!methods.length&&!baits.length;stats.innerHTML=noData?`<div class="intel-empty">Noch nicht genügend Communitydaten. Sobald Fänge mit Köder und Methode veröffentlicht werden, entstehen hier echte Gewässerstatistiken.</div>`:`<div class="intel-stats"><div class="intel-stat-card"><h4>Erfolgreiche Methoden</h4>${methods.length?barRows(methods):'<div class="intel-empty">Noch keine Methoden erfasst.</div>'}${pro?'':`<div class="intel-lock"><b>PRO · DETAILSTATISTIK</b><button onclick="window.openPro&&openPro()">Freischalten</button></div>`}</div><div class="intel-stat-card"><h4>Häufigste Köder</h4>${baits.length?barRows(baits):'<div class="intel-empty">Noch keine Köder erfasst.</div>'}${pro?'':`<div class="intel-lock"><b>PRO · KÖDERANALYSE</b><button onclick="window.openPro&&openPro()">Freischalten</button></div>`}</div></div><div class="intel-note">Basis: ${rows.length} öffentliche Fänge an diesem Gewässer.</div>`}
    if(!feed)return;if(!rows.length){feed.className='intel-empty';feed.style.padding='0 20px 20px';feed.textContent='Hier wurde in AngelLog noch kein öffentlicher Fang gepostet.';return}
    const recent=rows.slice(0,12),userIds=[...new Set(recent.map(x=>x.user_id).filter(Boolean))],ids=recent.map(x=>x.id);let profiles=[],likes=[],comments=[];
    await Promise.all([userIds.length?sb.from('profiles').select('id,username,display_name,avatar_url').in('id',userIds).then(x=>profiles=x.data||[]):Promise.resolve(),ids.length?sb.from('catch_likes').select('catch_id').in('catch_id',ids).then(x=>likes=x.data||[]):Promise.resolve(),ids.length?sb.from('catch_comments').select('catch_id').in('catch_id',ids).then(x=>comments=x.data||[]):Promise.resolve()]);if(token!==intelToken)return;
    const pm=new Map(profiles.map(p=>[p.id,p])),count=(arr,id)=>arr.filter(x=>x.catch_id===id).length;
    feed.className='';feed.style.padding='0';feed.innerHTML=recent.map(c=>{const p=pm.get(c.user_id)||{},name=p.display_name||p.username||'Angler',avatar=p.avatar_url?`<img src="${safe(p.avatar_url)}" alt="">`:safe(name.slice(0,1).toUpperCase());return `<article class="intel-catch"><div class="intel-user"><div class="intel-avatar">${avatar}</div><div><b>${safe(name)}</b><small>${safe(c.caught_on||'')}</small></div></div><div class="intel-catch-img">${c.photo_url?`<img src="${safe(c.photo_url)}" alt="Fang">`:'🐟'}</div><div class="intel-catch-main"><div><div class="intel-fish">${safe(c.species||'Fang')}</div><div class="intel-meta">${c.length_cm?`${safe(c.length_cm)} cm`:''}${c.weight_kg?` · ${safe(c.weight_kg)} kg`:''}${c.method?`<br>Methode: ${safe(methodName(c.method))}`:''}${c.bait?` · Köder: ${safe(c.bait)}`:''}</div></div><div class="intel-social">♡ ${count(likes,c.id)} · 💬 ${count(comments,c.id)}</div></div>${c.notes?`<p class="intel-meta">${safe(c.notes)}</p>`:''}</article>`}).join('');
  }
  async function loadIntel(id){const token=++intelToken,w=aaCurrentWater;if(!w||w.id!==id)return;const web=q('#aaWebsite');if(web){const url=w.official_url||w.association_url;if(url)web.innerHTML=`<a href="${safe(url)}" target="_blank" rel="noopener" style="color:var(--green)">Webseite öffnen</a>`;else web.textContent='–'}await Promise.allSettled([loadForecast(w,token),loadCommunity(id,token)])}
  async function saveCatchIntel(){if(!aaUser)return toast('Bitte zuerst anmelden.');const species=q('#aaSpecies')?.value.trim(),length=+q('#aaLength')?.value||null,weight=+q('#aaWeight')?.value||null,bait=q('#aaBait')?.value.trim()||null,method=q('#aaMethod')?.value||null,waterId=aaCurrentWater?.id||null,waterName=aaCurrentWater?.name||null,pref=window.getAngelLogPreferences?.()||{},visibility=q('#aaCatchVisibility')?.value||pref.default_catch_visibility||'public';if(!species)return toast('Fischart fehlt.');const {error}=await sb.from('catches').insert({user_id:aaUser.id,species,caught_on:new Date().toISOString().slice(0,10),length_cm:length,weight_kg:weight,bait,method,water_id:waterId,water_name:waterName,visibility});if(error)return toast(error.message);toast(visibility==='public'?'Fang veröffentlicht.':'Fang privat gespeichert.');closeAdd();if(waterId)loadIntel(waterId);loadFeed()}
  function hook(){inject();const original=window.openWater;if(typeof original==='function'&&!original.__intel){const wrapped=async function(id){await original(id);setTimeout(()=>loadIntel(id),60)};wrapped.__intel=true;window.openWater=wrapped}const save=q('#aaSaveCatch');if(save)save.onclick=saveCatchIntel}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(hook,0));else setTimeout(hook,0);
})();
